name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Go Project
      run: |
        # Add your Go build commands here
        go build cmd/main.go

    - name: Copy Files to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: main
        target: /root/www/backend

    - name: Restart Go Application on Server
      run: |
        # Add your command to restart the Go application on the server
        sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /root/www/backend && ./main"
